name: CD Pipeline
permissions:
  contents: read
  pull-requests: write
  id-token: write
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      - name: Set up kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Deploy to Kubernetes with Helm
        run: |
          helm upgrade --install devops-app ./helm/devops-app --namespace default