name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint avec Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lancer Flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  security:
    name: Analyse de sécurité avec Bandit
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"

      - name: Installer Bandit
        run: pip install bandit

      - name: Lancer Bandit (niveau HIGH uniquement)
        run: bandit -r src/app.py --severity-level high